### ISSUE TITLE
Cant start the daemon on ubuntu 22

### ISSUE THREAD

**Issue by makertronic** [LabyrinthCore/Labyrinth#1]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/85033212/208263214-8406ee31-8362-4151-a95c-dae18edc083a.png">

I have installed sudo apt-get install libboost-all-dev
But it's the 1.74 version. 

Any clue ?

**Comment by LabyrinthCore** [comment]
The precompiled binaries are for Ubuntu 20.04

**Comment by makertronic** [comment]
thanks. Have a nice day
